### ISSUE TITLE
Force vertical orientation

### ISSUE THREAD

**Issue by kenneho** [Eliav2/react-xarrows#107]
**Describe the solution you'd like**
Hi. First, thanks for this great library!
I'm building a folder structure type of functionality. Consider this screenshot: 
![image](https://user-images.githubusercontent.com/398761/139471707-f39ee7ad-9316-4d91-a948-7136d7742bb4.png)
There's lines going from the parent to the three children. I'd like a way to force the line coming out of the parent to be vertical all the way, and not first going horizontal before going vertical down towards the children. 

**Describe alternatives you've considered**
None. Don't know of any workarounds.

**Comment by Eliav2** [comment]
Try using gridbreak = 100%

**Comment by kenneho** [comment]
Thanks, I got it working now. Actually I had to set gridbreak to 0% instaed of 100% though, but it now looks perfect.
