### ISSUE TITLE
When drawling lines between mutiply layers, the lines becomes weired.

### ISSUE THREAD

**Issue by Even0311** [Eliav2/react-xarrows#150]
[comment]: <> (replace paragraphs text where needed)
**Describe the bug & Expected behavior**
When I am controlling the lines by expanding the parent element, the expected behaviour is start drawing lines between parent component and all the children components, however, when the kid itself as a parent component and drawing lines to its kid, it becomes weired
**To Reproduce**
Steps to reproduce the bug:  what props where used, in what way the lib was used?  
provide preferably minimal code snippets/codesandbox/gitpod.
Sorry it is inside a big project I cannot give you the link, however, you can see  the screen shoot.
**Screenshots**
![image](https://user-images.githubusercontent.com/23709903/182028469-4bf9d6dc-218c-43b5-b4b5-f1b655339831.png)

As you can see, Clicking the plus button will expand all its children. However, once expanded, the lines are not correct. The Xarrows are drawed by recurssion.

**Comment by Eliav2** [comment]
I cannot understand/debug the problem via screenshot
