### ISSUE TITLE
width line startAnchor and endAnchor

### ISSUE THREAD

**Issue by AlirezaBabaeii** [Eliav2/react-xarrows#156]
How to increase the width of the yellow dots?

I want something like the picture on the right (Purple color).

![xarrow](https://user-images.githubusercontent.com/99098510/194704806-f4f9061f-ce36-4407-95a3-cffcc81d1413.jpg)

**Comment by yashjais** [comment]
@AlirezaBabaeii Did you find any solution regarding this?

**Comment by Eliav2** [comment]
This is currently not supported. in a future release it will be. for now use invisible elements and multiple xarrows
