### ISSUE TITLE
Warnings that attribute "repeatCount" has unexpected value of "0"

### ISSUE THREAD

**Issue by DavidErben** [Eliav2/react-xarrows#160]
**Describe the bug & Expected behavior**

React Dev Tools show warnings that the attribute "repeatCount" has an unexpected value of 0.

![grafik](https://user-images.githubusercontent.com/79685270/203713168-819b8de5-59e1-4e49-9bb3-24f30839b0ef.png)

Setup:

```
    <Xarrow
      start={startElement}
      end={endElement}
      startAnchor={"right"}
      endAnchor={"left"}
      color={theme.palette.primary.main}
      curveness={0.5}
      showHead={true}
      animateDrawing={1}
      dashness={{ strokeLen: 10, nonStrokeLen: 10, animation: 1 }}
    />
```

According to Mozilla docs the value of the attribute must be either a value greater than 0 or "indefinite":

https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/repeatCount

HTML:

![grafik](https://user-images.githubusercontent.com/79685270/203712881-cb40d713-a5e3-4391-ad09-19f566ad892d.png)

Source code in XArrow.tsx:

![grafik](https://user-images.githubusercontent.com/79685270/203712824-f69e2b25-5b93-461f-ae0e-f85f8e42d7fe.png)

**To Reproduce**

Use setup above, but it should be easy to reproduce.

Version used: 2.0.2

**Comment by Eliav2** [comment]
this is not specific to react-xarrows

**Comment by DavidErben** [comment]
Could you please explain why this is not specific to "react-xarrows"? Isn't this warning coming from the code in the screenshot below?

If I use "showHead={false}", the warning goes away because the selected code is not rendered anymore. Wouldn't a valid value for "repeatCount" (f.e. "1" or "indefinite") in the heads <animate> element solve this? Or is there another way to fix this? Unfortunately there are no props which are passed down to this element, only for the head itself.

![grafik](https://user-images.githubusercontent.com/79685270/205941911-1f3c70fd-6d66-47e2-a3ee-4c5ac2933f4d.png)
