### ISSUE TITLE
Version 2.x.x not working in react 18 after build

### ISSUE THREAD

**Issue by RaresAil** [Eliav2/react-xarrows#191]
**Describe the bug & Expected behavior**

Version 2.x.x not working in react 18 after build

**To Reproduce**

Use react `18.0.0`, the latest `2.x.x`, and build it, to view the build version use serve or cloudflare pages

> Only version `1.7.2` works

**Comment by joealden** [comment]
You're going to need to provide a reproduction for this - we're using the latest version of both `react-xarrows` and `react` with no problems.
