### ISSUE TITLE
Better control over arrow layout?

### ISSUE THREAD

**Issue by bjmillsnsx** [Eliav2/react-xarrows#25]
In the attached image, you can see that I want to show a relationship between the first line and a couple of the lines below.  I want the arrows to approach from the right side of the elements.  As pictured, the arrows are trampling the content of my elements.  I'd like the arrows to be able to first travel far enough to the right so that they can attach to each element from the right.

![image](https://user-images.githubusercontent.com/38570476/89579012-0a718480-d801-11ea-95b2-1d926cea3c1e.png)

**Comment by NikZak** [comment]
I second that. I also need some fixed distance (eg in %) the arrow goes away first (in my case it is left, not right) and then comes back.

**Comment by oyalhi** [comment]
Just curious, doesn't the `endAnchor="right"` work for you? Assuming the below item is the `end`.

**Comment by Eliav2** [comment]
use gridBreak in v1.7

**Comment by Eliav2** [comment]
discussed in details in #70
