### ISSUE TITLE
Move arrow to "back" if element overlaps arrow

### ISSUE THREAD

**Issue by PhucNgo1711** [Eliav2/react-xarrows#31]
If I have box A, B, C, and I have an arrow pointing from A to C, but box B is in the path of the arrow. Right now the arrow path line would display on top of box B. It would be nice if the path line can be "moved to back" so that box B covers the line.

Not a bug, but enhancement.

**Comment by Eliav2** [comment]
not a bug, or an enhancement. you should use wisely with the z-index property. you can use passProps to pass props to the visible parts of the arrow.

**Comment by PhucNgo1711** [comment]
Sorry to bother you again but can you give me a small example?

**Comment by Eliav2** [comment]
Give create a small sandbox demonstratre your case and I will try

**Comment by PhucNgo1711** [comment]
Here is a codesandbox link for you
https://codesandbox.io/s/playground-7tug1?file=/src/examplesFiles/Example2.jsx

**Comment by PhucNgo1711** [comment]
Hi,

Have you had the chance to look at my sandbox yet?

**Comment by Eliav2** [comment]
Yes. But no success for now.
I would suggest a patience when I will have time I will look,
But for now I would suggest read about z index and about stack context in MDN (they have really great toturials), and try to use passProps property and advanced.passProps property.

**Comment by PhucNgo1711** [comment]
Okay thank you I'll do that

**Comment by PhucNgo1711** [comment]
I was able to figure this out using zindex. Thank you.

**Comment by Eliav2** [comment]
Great! Can you share?

**Comment by PhucNgo1711** [comment]
It's pretty simple actually (at least for my use case). I just set `position: "relative", zIndex=1` for the `div` that contains the boxes so they'll "float" on top of the arrows.
