### ISSUE TITLE
Published package with debug rect.

### ISSUE THREAD

**Issue by nikugogoi** [Eliav2/react-xarrows#33]
I am seeing a pink border rect when arrows are drawn diagonally. Probably published the package with debug rect element.
Issue can be seen in example 1 of https://codesandbox.io/embed/github/Eliav2/react-xarrows/tree/master/examples?fontsize=14&hidenavigation=1&theme=dark

**Comment by Eliav2** [comment]
You are completely right! Will be fixed right away!

**Comment by Eliav2** [comment]
V1.5.2 has released with a fix. v1.5.1 DEPRECATED. I accidentally wrote down 'npm publish' from dev branch and not master!
