### ISSUE TITLE
Ability to Pass Coordinates

### ISSUE THREAD

**Issue by amcdnl** [Eliav2/react-xarrows#38]
It would be nice if instead of a ref/id you could pass coordinates - example would be I want to drag a arrow from a div and have the end follow my mouse.

**Comment by Eliav2** [comment]
not sure where you wish to pass cordinates.
can you give a concrete example?

**Comment by Eliav2** [comment]
hey
see!
https://stackoverflow.com/questions/62408529/react-drag-drop-and-connect-arrowor-anything-else-with-animation-between-elem

probably exactly what you tried to achive

**Comment by amcdnl** [comment]
Oh - yes - this is great!
