### ISSUE TITLE
Apply custom svg as arrow 

### ISSUE THREAD

**Issue by kenzo23312** [Eliav2/react-xarrows#39]
Is it possible to apply custom svg instead of default arrow ? For example circle shape ?

**Comment by Eliav2** [comment]
will soon be available.

**Comment by Eliav2** [comment]
currently available in dev branch. you can pass `svgHead="circle"` or supply detailed object. this option is not yet documented, but could understand it from the CustomizeArrow.tsx example and from the source.(gitpod the dev branch and see!)
