### ISSUE TITLE
Option for Parallel Lines

### ISSUE THREAD

**Issue by vinnymicale** [Eliav2/react-xarrows#40]
Hey!

I think it would be a great addition to have the option of having parallel lines in the case of something like:

- Line from '#id1' to '#id2'
- Line from '#id2' to '#id1'

Currently, if this is the case, the lines would show as overlapping each other, since they'd both be taking the shortest path when using automatic anchors.

Although basic, I had something like this in mind:

![parallel lines](https://user-images.githubusercontent.com/43476785/103803526-adcbfd00-501e-11eb-9e4f-527341249a76.PNG)

**Comment by Eliav2** [comment]
you can absolutely do it with the current API, just pass `offset` the anchors similar to the example [here](https://github.com/Eliav2/react-xarrows#startanchor-and-endanchor).

**Comment by vinnymicale** [comment]
Hey thanks for the response - that was one of the things I had tried originally, and it does seem to work well, but in the case of the example I had in my first post where the elements are aligned horizontally, passing an offset (with rightness, for example), will cause the lines to render a bit diagonally instead of a straight/vertical line between the two elements. It doesn't seem like changing the position would help fix this at all. Not a huge issue, but since the original point can be accomplished with an offset,  are there any solutions to not have the lines be diagonal?

**Comment by mkhoussid** [comment]
@Eliav2 Are you talking about this component [here](https://github.com/Eliav2/react-xarrows/blob/master/examples/src/components/DraggableBox.tsx)? The property `offset` doesn't exist.
