### ISSUE TITLE
Does not stick when the element is resized

### ISSUE THREAD

**Issue by pachu4u** [Eliav2/react-xarrows#44]
Hi,

It works great if the element is moved its position. However if the element resized (width or height changed), it does not stick to its boundary.

**Comment by Eliav2** [comment]
Please provide appropriate details and codesandbox

**Comment by gynekolog** [comment]
@pachu4u Isn't it what [documentation say](https://github.com/Eliav2/react-xarrows#usage):
```
react-xarrows does not renders automatically if one of the connected elements is rendered.
```
?

You can solve it by forcing re-render your component contains xarrows components. Something like:
```
export const Page = () => {
  useWindowSize(); // https://usehooks.com/useWindowSize/

  const firstRef = useRef<HTMLDivElement>(null);
  const secondRef = useRef<HTMLDivElement>(null);

  return (
    <div>
      <div ref={firstRef} />
      <div ref={secondRef} />

      <Xarrow start={firstRef} end={secondRef} />
    </div>
  );
};

```

**Comment by Eliav2** [comment]
if no respond for few days i will close this issue
