### ISSUE TITLE
Path "GRID" overlaps with node when connected to parent 

### ISSUE THREAD

**Issue by jithureddy** [Eliav2/react-xarrows#48]
Hi, 
Firstly, I would really appreciate creating this library. Thanks a ton!!! 
I have an issue with grid type path, some of the lines are connected to line under the top rows nodes as shown below. I think this is issue with shorted path to connect the lines.
![image](https://user-images.githubusercontent.com/5911189/109819369-e4dc1a80-7c2b-11eb-970f-5fe8b00e9e14.png)

If we see the below screenshot, need to move some lines in between nodes 
![image](https://user-images.githubusercontent.com/5911189/109820067-90856a80-7c2c-11eb-81d0-cbb8c06fbffd.png)

Please help. Thanks

**Comment by Eliav2** [comment]
I friend thank you for opening this issue.
can you provide some code?(you can share publically by codesandbox or privately giving me access to your code via github)

**Comment by jithureddy** [comment]
@Eliav2 Well, for me I cannot disclose the code for the above use case. Also I cannot notice this issue when I layout the grid properly. Also I am using tailwind css, I need to setup the codesandbox for that, so would take time for that. I will do once I get free time.

**Comment by Eliav2** [comment]
You Can probably copy all your src files to code sandbox and it should work

**Comment by Eliav2** [comment]
any update? i dont think its a bug in my component

**Comment by Eliav2** [comment]
Use the new property `gridBreak` with v1.7, that should solve it.
