### ISSUE TITLE
onClick events not firing correctly

### ISSUE THREAD

**Issue by tsaockham** [Eliav2/react-xarrows#50]
Hello, when I test with both chrome and Firefox on a mac, with the following code, I don't seem to be getting a consistent onClick event, nor does the arrow head fire an event.  Am I doing something wrong? Any thoughts?

https://codesandbox.io/s/xarrows-onclick-issue-z8lgv?file=/src/App.js

Thank you very much! excellent library apart from this issue.

**Comment by Eliav2** [comment]
see: https://codesandbox.io/s/xarrows-onclick-issue-forked-twx1v?file=/src/App.js
you need to pass `pointerEvents: "all"` to the arrow head. I've changed it in the dev branch to be the default behavior so in the next release it will be the defualt.

**Comment by tsaockham** [comment]
Works great, thank!
