### ISSUE TITLE
Avoid drawing over specific items or ids

### ISSUE THREAD

**Issue by PatrickMennen** [Eliav2/react-xarrows#66]
**Is your feature request related to a problem? Please describe.**
I would love if it was possible to take the boundaries of specific other components in to account when rendering the arrows between components to avoid overlap with objects available. Ideally it would be an array of refs or ids to avoid.

I know this complicates the algorithm significantly, but just passing extra props to the component in its current state seems to be not sufficient (or am I missing something?)

<img width="376" alt="image" src="https://user-images.githubusercontent.com/7114798/116356299-6353d380-a7fb-11eb-9b1c-88003a088073.png">

**Describe the solution you'd like**
The possibility for the lines to avoid touching the other elements (so the blue line from top to bottom would go around both other "appointments"

**Comment by Eliav2** [comment]
This is too complicated to implement it the moment. This Lib is hoby and not my job. You can try to do it by your self.
