### ISSUE TITLE
The arrow does not point to the correct location once its outer div has a changed scale.

### ISSUE THREAD

**Issue by MarijnRitzen** [Eliav2/react-xarrows#67]
When you are working with some kind of zoom ui library, the arrows initially scale with the rest of the html. But once you start to move one of the divs that the arrow is attached to, the arrow updates itself wrongly, not taking into account the scale on the outer div

**Comment by Eliav2** [comment]
This is not how you open issue. If you want help with your problam be specific and provide code sandbox example

**Comment by MarijnRitzen** [comment]
Yeah sorry, it's also fixed using the scale prop. I had to do scale={1/ZoomFactor} where zoomfactor is the css scale transform of a parent element of xarrow

**Comment by Eliav2** [comment]
If you solve the problem you can provide more information for other people that may faced this issue as well, and then close the issue.
