### ISSUE TITLE
Visual glitch while dragging on grid

### ISSUE THREAD

**Issue by pmorim** [Eliav2/react-xarrows#71]
[comment]: <> (replace paragraphs text where needed)
**Describe the bug & Expected behavior**
Using `react-draggable` with a grid, I get a visual glitch where the connection is connected to the last place where the component was. This only happens while dragging. After the component is "dropped", the connection updates to the correct place.

I assumed this is a bug with `react-xarrows`, but it might be with `react-draggable`'s `onDrag` prop. I also assume that the bug is always present, but the gap is so small that it isn't noticed when there is no grid.

**To Reproduce**
Simply use `react-draggable` with a grid.

Here is a link to an example on CodeSandbox: https://codesandbox.io/s/react-xarrows-bug-81lx4?file=/src/App.js.
If you prefer, here is the code: 
```javascript
import { useState } from "react";
import Draggable from "react-draggable";
import Xarrow from "react-xarrows";
import "./styles.css";

function App() {
  const [, setRender] = useState({});
  const reRender = () => setRender({});

  return (
    <div className="App">
      <Xarrow start="1" end="2" path="grid" showHead={false} />

      <Draggable
        defaultPosition={{ x: 60, y: 60 }}
        grid={[20, 20]}
        onStop={reRender}
        onDrag={reRender}
      >
        <div id="1" className="square" />
      </Draggable>

      <Draggable
        defaultPosition={{ x: 300, y: 300 }}
        grid={[20, 20]}
        onStop={reRender}
        onDrag={reRender}
      >
        <div id="2" className="square" />
      </Draggable>
    </div>
  );
}

export default App;
```

**Screenshots**
Here is a screenshot of what happens while dragging the component.

![bug](https://trello-attachments.s3.amazonaws.com/6003170aa73ade7cadecec17/60abc3b60c774e5104f40e22/4b7870aa97f2b66cea92b176785334fd/teste.png)

**Comment by Eliav2** [comment]
Interesting... Thanks! will investigate it soon

**Comment by Eliav2** [comment]
It seems that when using grid react-draggable is updating the state and at the same time react-xarrows taking current Dom properties so react-xarrows and react-draggable updating themself by the same frame when actually react-xarrows needs to take the frame after draggable.

in current version there is no way around via the API. but can force 2 renders each update and this will fix at, not a pretty solution, but it is working workaround, see:
https://codesandbox.io/s/react-xarrows-bug-fixforked-m60yc?file=/src/App.js

maybe on next release I will add a property for a callback function on the effects stage for xarrow so you could force reupdating manylly, at will still force 1 more render but would be more convenient to do so via the API.

thanks for the demo

**Comment by pmorim** [comment]
Thank you for the quick response. This workaround works fine.
