### ISSUE TITLE
TypeError: Cannot read property 'getBoundingClientRect' of null

### ISSUE THREAD

**Issue by jbcabreras** [Eliav2/react-xarrows#77]
Hi guys, hope you are doing well.
It seems like after updating react-xarrows to the latest version (1.7.0) we get this null ref. when passing the string IDs to the "start" and  "end" props.

<img width="1107" alt="xarrow" src="https://user-images.githubusercontent.com/9064599/121082989-3d83fc00-c7b5-11eb-8097-a78f4157887d.png">

any ideas about this?

**Comment by Eliav2** [comment]
can you provide an example of when it happens?

**Comment by georgeweiler** [comment]
@Eliav2 I am also seeing this error after updating. In my case, I am rendering several xarrows between nodes in a map. 

```const Component = () => {
  const data = new Array(5).map((_, i) => {
    return {
      id: `item-${i}`,
      start: `item-${i}`,
      end: `item-${i + 1}`,
    };
  });

  return (
    <>
      {data.map(({ id, start, end }) => {
        // document.getElementById(start) === null
        // document.getElementById(end) === null

        return (
          <>
            {/* this div is a node to draw an xarrow between */}
            <div id={id} />

            <Xarrow key={id} start={start} end={end} />
          </>
        );
      })}
    </>
  );
};
```

**Comment by menasiephrem** [comment]
I am facing the same issue. seems like ```getElementByPropGiven``` doesn't check for null values, i.e. if the id is not in the dom.

**Comment by Eliav2** [comment]
I need full working example to debug and release a patch. can one of you upload minimal code sandbox reproducing this issue?

currently, I'm working on the next big update but I can patch and release v1.7.1 with fix

**Comment by Eliav2** [comment]
This problem was related to the refs to the connected element that was not present.
v1.7.1: now the arrow will not be drawn and the app will not crush and prop-type error will raise
