### ISSUE TITLE
Enhancement to Custom SVG

### ISSUE THREAD

**Issue by troy191990** [Eliav2/react-xarrows#81]
**Is your feature request related to a problem? Please describe.**
I love the feature that was added where I can customize my arrow head/tail with a custom SVG, however I am very limited in my knowledge/ability of creating complex SVG files in code. 

I have a graphics designer who creates them for me, however I am unable to use them with xarrows. 

Id love the ability to pass in a "ready-made" svg as a custom one. Rather than having to create it using typescript properties.

**Comment by Eliav2** [comment]
accepted. added to the dev branch and will be published with v2.

**Comment by troy191990** [comment]
I see your change in v2, which allows for svg elements. Is that change in reference to this item? If so, I have tried to use the feature, however am unable to get the desired results. Am I using this correctly?
https://qx7pj.csb.app/

I have commented out the custom "headShape" property. I have also attached the svg image.

**Comment by Eliav2** [comment]
No, you using it wrong, you should pass object with property svgelem, go read the api again

**Comment by Eliav2** [comment]
you have to adjust the SVG shape.
the docs state: "in case you pass a custom svg element: currently you have to adjust the path to start from 0,0 and to be at size box 1x1 in order to make the custom shape look like the default shapes in size". your SVG shape is much bigger.

an automatic adjustment is available in a not yet released pro version of react-xarrows.

**Comment by troy191990** [comment]
Please can you provide a codesandbox or example of doing this, I read the documentation and have tried to do as instructed, but am hitting a wall.

**Comment by Eliav2** [comment]
I will support you with your case for a donation

**Comment by troy191990** [comment]
Sure. Il make a donation now.
