### ISSUE TITLE
v2 not as expected on react StrictMode?

### ISSUE THREAD

**Issue by logankfuller** [Eliav2/react-xarrows#82]
[comment]: <> (replace paragraphs text where needed)
**Describe the bug & Expected behavior**
After creating a new project and installing the newest version (2.0.0), the examples do not run, quoting an error: "Uncaught Error: 'Xwrapper' is required around element using 'useXarrow' hook! wrap your xarrows and connected elements with Xwrapper! "

**To Reproduce**
All I did was create a new project, install the libraries (react-xarrows and react-draggable) and copy/paste the example code.

I did this in CodeSandbox as well: [CodeSandbox](https://codesandbox.io/s/hungry-tu-06cwm?file=/src/App.js)

**Screenshots**
[Link to Error](https://imgur.com/a/0pfCjRf)

**Comment by Eliav2** [comment]
Your are right.. this is very stange; if you will copy and paste the example and replace the code of 'simple example' with this code at will work

**Comment by logankfuller** [comment]
Hey,

I've played around with the code a bit, but I'm not quite sure what you're asking. I've copied/pasted various parts and I still get the same error. Can you paste an example?

**Comment by Eliav2** [comment]
see
https://codesandbox.io/s/react-arrows-v2-works-qbpyv?file=/src/index.jsx
seems to work perfectly fine here.

**Comment by Eliav2** [comment]
whatt
strange!
StrictMode breaks v2
https://codesandbox.io/s/react-arrows-v2-strictmode-not-work-ko4ju?file=/src/index.jsx

i have no idea why, but `StrictMode` that create-react-app uses by default breaks react-xarrows v2.
currently, to resolve just remove the wrapping `StrictMode` wrapper as a workaround until I will figure it out and would release a patch.

**Comment by logankfuller** [comment]
Yeah that seemed to be the fix. Thanks!

> whatt
> strange!
> StrictMode breaks v2
> https://codesandbox.io/s/react-arrows-v2-strictmode-not-work-ko4ju?file=/src/index.jsx
> 
> i have no idea why, but `StrictMode` that create-react-app uses by default breaks react-xarrows v2.
> currently, to resolve just remove the wrapping `StrictMode` wrapper as a workaround until I will figure it out and would release a patch.

**Comment by Eliav2** [comment]
Open. This should be fixed

**Comment by Eliav2** [comment]
related 
https://github.com/facebook/react/issues/21956
