### ISSUE TITLE
Arrow reposition fails when container style has `transform: scale(0.5);`

### ISSUE THREAD

**Issue by mattlo** [Eliav2/react-xarrows#87]
**Describe the bug & Expected behavior**
Arrow reposition fails when container is using `transform: scale(0.5);`.

**To Reproduce**

1. Add a container div with `<div style={{transform: 'scale(0.5)'}}>`
2. See arrows not in correct position

**Screenshots**
![transform breaks position](https://user-images.githubusercontent.com/1714244/128237901-55719563-3cad-4bf0-ac94-2f1195e0217a.gif)

**Comment by mattlo** [comment]
I was able to reproduce this on the example sandbox as well: 

<img width="1437" alt="Screen Shot 2021-08-04 at 1 56 48 PM" src="https://user-images.githubusercontent.com/1714244/128239077-3921f47e-d071-407e-a85c-e7790d366ad7.png">

It might have something to do with recalculating whenever there's a style chance. I think on the initial render, it usually works fine.

**Comment by Eliav2** [comment]
Thank you. Will soon take a look

**Comment by Eliav2** [comment]
please refer
https://github.com/Eliav2/react-xarrows/issues/30
does this solves it

**Comment by mattlo** [comment]
Yeah, it always works outside the scaled `<div />` but the bug is when it's inside. I'm assuming scaling any elements containing an arrow is simply not supported.
