### ISSUE TITLE
Forwarding ref

### ISSUE THREAD

**Issue by pmorim** [Eliav2/react-xarrows#88]
**Is your feature request related to a problem? Please describe.**
I'm trying to get the `.getBoundingClientRect()` of the `<XArrow />` component so that I can get its width, height, etc...
The problem is that there is no way - that I know of - to get a ref of the Arrow.

**Describe the solution you'd like**
There should be a way to add a ref like:

```jsx
const App = () => {
  const ref = useRef()
  // ...

  return (
    <XArrow
      start={start}
      end={end}
      ref={ref} // 👈 Passing the ref as prop
    />
  )
}
```
This can be achieved by defining the `XArrow` component with `forwardRef`.

**Describe alternatives you've considered**
I tried applying the ref to a wrapping div (see code below), but it did not work.

```jsx
const App = () => {
  const ref = useRef()
  // ...

  return (
    // 👇 ref being applied to the wrapper div
    <div ref={ref}>
      <XArrow
        start={start}
        end={end}
      />
    </div>
  )
}
```

**Additional context**
Are there any workarounds for this? I need to finish an app fast and can't really wait for a proper fix.

**Comment by Eliav2** [comment]
You don't want to forward ref, you probably want to pass ref to the div container. Go ahead and try passing ref to divContainerProps. Please read advanced customization

**Comment by pmorim** [comment]
I already had tried doing that, but I always got an error on the console.
Besides that, the `rect` would come with `{ ..., width: 0, height: 0 }`.

Here is a CodeSandbox that shows what is happening: https://codesandbox.io/s/react-xarrows-bug-arrow-ref-z1tkr?file=/src/Connection.jsx.

**Comment by Eliav2** [comment]
To get the size of the arrow you should pass ref to svgprops
Does you solved the issue?

**Comment by Eliav2** [comment]
oh yeah.. you can't pass this prop because you overwrite 'ref' which is used internally by react-xarrow ...
this means that in the current version you can not access the ref. there might be a way around it and I will think about it for next release.

**Comment by LucaH612** [comment]
@joealden you can access all properties of the Xarrow-SVG by giving a ref to a parent div. Then you will just have to get the child of the div, and you can access all dimensions, path, etc.

**Comment by joealden** [comment]
@LucaH612 indeed - and this is how I worked around this, but I think it'd be better if this was exposed by `react-xarrows`, as it'd avoid some of the logic I need to have in an effect handler (as the path will change on container resize etc.), and I think it'd mean less type casting in TypeScript!
