### ISSUE TITLE
The arrow overlaps over other div contents

### ISSUE THREAD

**Issue by kmartin62** [Eliav2/react-xarrows#91]
Hey, I've been using this library for a while and it looks great. However recently one of the arrows keeps overlapping my div content and it doesn't look good. I've tried the **zIndex** functionality but still the same. Is there something I'm doing wrong or it's something under development?

**Comment by Eliav2** [comment]
Did you solved your issue?

**Comment by kmartin62** [comment]
> Did you solved your issue?

No, for now I placed my components on places where they won't overlap with the arrow. Anyway, is there a plan for a feature like this to be added?

**Comment by Eliav2** [comment]
If you want better help you should construct minimal sandbox
